function fibonacci( n ) {
    (if (lte n 1) (return n))
    (return (add (fibonacci (sub n 2)) (fibonacci (sub n 1))))
    // (set n (add (fibonacci (sub n 2)) (fibonacci (sub n 1))))
    // ("ANS " n ")")
    // (return n)
    // if (n <= 1) return n;
    // return fibonacci(n - 2) + fibonacci(n - 1);
}

function main() {
    ("Fibonacci(34): ")
    (print (fibonacci 34)) // = 5702887 (5,702,887)
    ("\n")
}